# Generated by Django 3.0.6 on 2020-05-09 17:21

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_score',
            field=models.FloatField(blank=True, null=True, validators=[classroom.models.positive_float_validator]),
        ),
    ]
